FROM node:20

WORKDIR /app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm install --ignore-scripts

ADD ./prisma ./prisma

RUN npm run prepare

ADD ./ ./

CMD npm run start:docker
